FROM php:8.4.19-cli AS beam_assets

ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_HOME=/composer \
    YARN_CACHE_FOLDER=/yarn \
    PATH=/composer/vendor/bin:/root/.yarn/bin:$PATH

# Beam's public/vendor assets are generated by Composer scripts and Yarn. The
# Nginx image serves the public directory directly, so build those artifacts in
# this stage instead of copying the unbuilt checkout.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential ca-certificates curl git libicu-dev libjpeg-dev \
        libonig-dev libpng-dev libssl-dev libzip-dev libsasl2-dev unzip \
        zlib1g-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-configure gd --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j"$(nproc)" bcmath gd intl mbstring pdo_mysql pcntl zip \
    && curl -fsSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && npm install --global yarn@v2 \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /composer/cache /yarn /var/www/html

WORKDIR /var/www/html
COPY Composer ./Composer
COPY Package ./Package
COPY Beam ./Beam

WORKDIR /var/www/html/Beam
RUN composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader \
    && (yarn install --immutable || yarn install) \
    && yarn run production

FROM nginx:stable

RUN apt-get update \
    && apt-get install -y --no-install-recommends gettext-base ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html
COPY --from=beam_assets /var/www/html/Beam/public ./Beam/public
COPY Campaign/public ./Campaign/public
COPY Mailer/www ./Mailer/www
COPY Sso/public ./Sso/public
COPY Docker/adminer ./Docker/adminer
COPY caprover/nginx/remp-caprover.conf.template /etc/nginx/templates/remp-caprover.conf.template

ENV NGINX_PORT=80 \
    CAMPAIGN_FPM=srv-captain--st-remp-campaign:9000 \
    MAILER_FPM=srv-captain--st-remp-mailer:9000 \
    BEAM_FPM=srv-captain--st-remp-beam:9000 \
    SSO_FPM=srv-captain--st-remp-sso:9000 \
    TRACKER_UPSTREAM=srv-captain--st-remp-tracker:8081 \
    SEGMENTS_UPSTREAM=srv-captain--st-remp-segments:8082 \
    MAILHOG_UPSTREAM=srv-captain--st-remp-mailhog:8025 \
    KIBANA_UPSTREAM=srv-captain--st-remp-kibana:5601

CMD ["/bin/sh", "-c", "envsubst '$$NGINX_PORT $$CAMPAIGN_FPM $$MAILER_FPM $$BEAM_FPM $$SSO_FPM $$TRACKER_UPSTREAM $$SEGMENTS_UPSTREAM $$MAILHOG_UPSTREAM $$KIBANA_UPSTREAM' < /etc/nginx/templates/remp-caprover.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
